<a href="https://colab.research.google.com/github/evermover/women_cloth_reviews_pred/blob/main/women_cloth_reviews_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/content/Women Clothing E-Commerce Review.csv")

In [4]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [6]:
df.shape

(23486, 10)

In [8]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [9]:
df[df['Review']==""] = np.NaN

In [10]:
df['Review'].fillna("No Review", inplace =True)

In [11]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [12]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

Define Target and Features

In [13]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [18]:
X= df['Review']
y = df['Rating']

In [15]:
df['Rating'].value_counts

<bound method IndexOpsMixin.value_counts of 0        4.0
1        5.0
2        3.0
3        5.0
4        5.0
        ... 
23481    5.0
23482    3.0
23483    3.0
23484    3.0
23485    5.0
Name: Rating, Length: 23486, dtype: float64>

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, stratify=y, random_state=2529)

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((18788,), (4698,), (18788,), (4698,))

Feature text conversion to Tokens

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv=CountVectorizer(lowercase = True, analyzer ='word',ngram_range=(2,3), stop_words='english', max_features=5000)

In [29]:
X_train = cv.fit_transform(X_train)

In [30]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [31]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
X_test = cv.fit_transform(X_test)

In [33]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'yesterday love',
       'yesterday store', 'yoga pants'], dtype=object)

In [34]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Get Model Train

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [41]:
model = MultinomialNB()

In [42]:
model.fit(X_train, y_train)

MultinomialNB()

In [43]:
y_pred = model.predict(X_test)

In [44]:
y_pred.shape

(4698,)

In [45]:
y_pred

array([5., 5., 5., ..., 3., 5., 3.])

Get Probability of Each predicted class

In [46]:
model.predict_proba(X_test)

array([[3.73675627e-02, 2.73950056e-02, 7.49474000e-02, 7.78324975e-02,
        7.82457534e-01],
       [2.05130359e-02, 1.78057391e-02, 8.36808673e-03, 9.91980455e-04,
        9.52321158e-01],
       [4.36395581e-02, 3.74123835e-03, 2.19781715e-01, 4.41379408e-03,
        7.28423694e-01],
       ...,
       [1.95559781e-02, 1.56259672e-01, 6.61439468e-01, 1.35019171e-03,
        1.61394690e-01],
       [1.05935112e-02, 9.87538607e-02, 1.05091501e-01, 5.28906015e-02,
        7.32670526e-01],
       [1.39702129e-03, 5.87642218e-03, 8.45432615e-01, 1.47100686e-01,
        1.93255582e-04]])

Get Model Evaluation

In [48]:
from sklearn.metrics import confusion_matrix, classification_report

In [50]:
print(confusion_matrix(y_test,y_pred))

[[  17   10   16   26   99]
 [  34   30   39   65  145]
 [  75   53   80  111  255]
 [ 141   51  124  215  485]
 [ 330  165  261  412 1459]]


In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.10      0.04       168
         2.0       0.10      0.10      0.10       313
         3.0       0.15      0.14      0.15       574
         4.0       0.26      0.21      0.23      1016
         5.0       0.60      0.56      0.58      2627

    accuracy                           0.38      4698
   macro avg       0.23      0.22      0.22      4698
weighted avg       0.42      0.38      0.40      4698



Recatagorize Ratings as Poor(0) and good(1)

In [53]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

Rerating 1,2,3 as 0 and 4,5 as 1

In [54]:
df.replace({'Rating': {1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [55]:
y=df['Rating']

In [56]:
x=df['Review']

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, stratify=y, random_state=2529)

In [59]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((18788,), (4698,), (18788,), (4698,))

Feature text conversion to Tokens

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

In [61]:
cv=CountVectorizer(lowercase = True, analyzer ='word',ngram_range=(2,3), stop_words='english', max_features=5000)

In [62]:
X_train = cv.fit_transform(X_train)

In [63]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [64]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [65]:
X_test = cv.fit_transform(X_test)

In [66]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 12 ordered', ..., 'years ago', 'years come',
       'yoga pants'], dtype=object)

In [67]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Let's Retraing this model

In [68]:
from sklearn.naive_bayes import MultinomialNB

In [69]:
model = MultinomialNB()

In [70]:
model.fit(X_train, y_train)

MultinomialNB()

In [71]:
y_pred = model.predict(X_test)

In [72]:
y_pred.shape

(4698,)

In [73]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

Get Probability of Each predicted class

In [74]:
model.predict_proba(X_test)

array([[0.04445186, 0.95554814],
       [0.03603202, 0.96396798],
       [0.22671988, 0.77328012],
       ...,
       [0.09017069, 0.90982931],
       [0.23127308, 0.76872692],
       [0.00399735, 0.99600265]])

Get Model Evaluation

In [75]:
from sklearn.metrics import confusion_matrix, classification_report

In [76]:
print(confusion_matrix(y_test,y_pred))

[[ 252  804]
 [ 687 2955]]


In [77]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.27      0.24      0.25      1056
         1.0       0.79      0.81      0.80      3642

    accuracy                           0.68      4698
   macro avg       0.53      0.53      0.53      4698
weighted avg       0.67      0.68      0.68      4698

